name: newwave_project
description: a project test for Newwave.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc:
  freezed_annotation:
  dio:
  get_it:
  collection: 1.17.0
  cupertino_icons: ^1.0.2
  cached_network_image: 3.2.3
  fl_paging: ^2.2.0
  tuple: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  freezed:
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
flutter_intl:
  enabled: true
